import { Joi } from 'joi'

export const productValidation = {
  id: Joi.string().uuid().required(),

  create: Joi.object({
    name: Joi.string().min(1).max(255).required(),
    description: Joi.string().min(1).max(2000).required(),
    shortDescription: Joi.string().min(1).max(500).required(),
    price: Joi.number().positive().required(),
    companyId: Joi.string().uuid().required(),
    categoryId: Joi.string().uuid().optional(),
    costPrice: Joi.number().positive().optional(),
    sku: Joi.string().alphanum().min(3).max(50).optional(),
    barcode: Joi.string().alphanum().min(8).max(20).optional(),
    stockQuantity: Joi.number().integer().min(0).default(0),
    minStockLevel: Joi.number().integer().min(0).default(0),
    maxStockLevel: Joi.number().integer().min(0).optional(),
    width: Joi.number().positive().optional(),
    height: Joi.number().positive().optional(),
    length: Joi.number().positive().optional(),
    depth: Joi.number().positive().optional(),
    weight: Joi.number().positive().optional(),
    grossWeight: Joi.number().positive().optional(),
    imageUrl: Joi.string().uri().optional(),
    imageAltText: Joi.string().max(255).optional(),
    isActive: Joi.boolean().default(true),
    isFeatured: Joi.boolean().default(false),
    isDigital: Joi.boolean().default(false),
    slug: Joi.string().alphanum().min(3).max(100).optional(),
    metaTitle: Joi.string().max(255).optional(),
    metaDescription: Joi.string().max(500).optional(),
  }),

  update: Joi.object({
    name: Joi.string().min(1).max(255).optional(),
    description: Joi.string().min(1).max(2000).optional(),
    shortDescription: Joi.string().min(1).max(500).optional(),
    price: Joi.number().positive().optional(),
    companyId: Joi.string().uuid().optional(),
    categoryId: Joi.string().uuid().optional(),
    costPrice: Joi.number().positive().optional(),
    sku: Joi.string().alphanum().min(3).max(50).optional(),
    barcode: Joi.string().alphanum().min(8).max(20).optional(),
    stockQuantity: Joi.number().integer().min(0).optional(),
    minStockLevel: Joi.number().integer().min(0).optional(),
    maxStockLevel: Joi.number().integer().min(0).optional(),
    width: Joi.number().positive().optional(),
    height: Joi.number().positive().optional(),
    length: Joi.number().positive().optional(),
    depth: Joi.number().positive().optional(),
    weight: Joi.number().positive().optional(),
    grossWeight: Joi.number().positive().optional(),
    imageUrl: Joi.string().uri().optional(),
    imageAltText: Joi.string().max(255).optional(),
    isActive: Joi.boolean().optional(),
    isFeatured: Joi.boolean().optional(),
    isDigital: Joi.boolean().optional(),
    slug: Joi.string().alphanum().min(3).max(100).optional(),
    metaTitle: Joi.string().max(255).optional(),
    metaDescription: Joi.string().max(500).optional(),
  }).min(1),

  list: Joi.object({
    page: Joi.number().integer().min(1).default(1),
    pageSize: Joi.number().integer().min(1).max(100).default(10),
    search: Joi.string().max(255).optional(),
    categoryId: Joi.string().uuid().optional(),
    companyId: Joi.string().uuid().optional(),
    isActive: Joi.boolean().optional(),
    minPrice: Joi.number().positive().optional(),
    maxPrice: Joi.number().positive().optional(),
    orderBy: Joi.string().valid('name', 'price', 'createdAt', 'updatedAt', 'stockQuantity').default('createdAt'),
    orderDirection: Joi.string().valid('ASC', 'DESC').default('DESC'),
  }),
}